global:
  openshift: true
  tlsDisable: false

ui:
  enabled: true

server:
  extraEnvironmentVars:
    VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt


  route:
    enabled: true
    host: vault-vault.apps.${cluster_base_domain}

  extraVolumes:
    - type: secret
      name: vault-server-tls # Matches the ${SECRET_NAME} from above

  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
        tls_client_ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
      }

      storage "file" {
        path = "/vault/data"
      }    

  service: 
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: vault-server-tls